language: node_js
node_js:
  - "node"
  - "8.11.4"
install:
  - npm install

script: npm run build

deploy:
  provider: firebase
  token:
    secure: "1/Kl_zjRXm5i9bLJTxOf-duTD3I-gdM548naSugyX34II"
  skip_cleanup: true