language: node_js
node_js:
  - "node"
  - "8.11.4"
install:
  - npm install

script: npm run-script build

deploy:
  provider: heroku
  api_key:
    secure: 71829136-89ea-446a-ad67-414010e627ec
    app: spm-sms