language: node_js
node_js:
  - "node"
  - "8.11.4"
install:
  - npm install

script: npm run-script build

deploy:
  provider: heroku
  api_key:
    secure: 5d7f5822-6aa7-4cd1-93ec-93bdc88e3158
    app: spm-sms